### ISSUE TITLE
Ability to pass options

### ISSUE THREAD

**Issue by genu** [lewebsimple/nuxt-graphql-codegen#5]
Are you open to a PR that allows passing a `configPath`? 

Currently it seems to only look for a codegen in the root of the project.

**Comment by lewebsimple** [comment]
Sure! I'll also bump the minor version and publish on npm

**Comment by jonatandorozco** [comment]
any updates on this?

**Comment by genu** [comment]
This project doesn't seem to get a lot of love. I ended up working another fork based on this. 

I recommend checking it out if you want something similar to this: https://github.com/genu/nuxt-codegen  or, if you want a more feature rich solution, also have a look at: https://github.com/Diizzayy/nuxt-graphql-client

Both are based on codegen.

**Comment by lewebsimple** [comment]
Yeah sorry about the lack of attention to this project, I ended up executing the codegen with a separate script in package.json to speed things up.

I recommend using the fork or nuxt-graphql-client and will archive this repository.
